#
# Mole fraction of A
A_RAW: 0.5

# Thermo model
GIBBS: FH

# Materials
MATERIAL_CHOICE: Validation

#Numerics
NOISE_MAGNITUDE: 0.01
TIME_MAX: 400000
DT: 2.0
N_CELLS: 128
DOMAIN_LENGTH: 128
theta_ch: 1
TIME_STRIDE: 5000
MESH_TYPE: structured
FINITE_ELEMENT: CG
FINITE_ELEMENT_ORDER: 1
SOLVER_CONFIG: LU


# PS_PMMA
## FH
chi_AB_PS_PMMA: 0.004
N_A_PS_PMMA: 2690
N_B_PS_PMMA: 4000

## PC_SAFT


# PS_PB
## FH
chi_AB_PS_PB: 0.08
N_A_PS_PB: 2690
N_B_PS_PB: 7780

# Sweeping Residual
DESIRED_RESIDUAL: 0.1

# Validation
## FH
chi_AB_Validation: 0.0075
N_A_Validation: 400
N_B_Validation: 400
