#
# Mole fraction of A
A_RAW: 0.4

# Thermo model
GIBBS: FH

# Materials
MATERIAL_CHOICE: PS_PB

#Numerics
NOISE_MAGNITUDE: 0.01
TIME_MAX: 200000
DT: 0.5
N_CELLS: 5
DOMAIN_LENGTH: 5
theta_ch: 1
TIME_STRIDE: 10000
MESH_TYPE: structured
FINITE_ELEMENT: CG
FINITE_ELEMENT_ORDER: 1
SOLVER_CONFIG: LU


# PS_PMMA
## FH
chi_AB_PS_PMMA: 0.009
N_A_PS_PMMA: 2690
N_B_PS_PMMA: 4000

## PC_SAFT


# PS_PB
## FH
chi_AB_PS_PB: 0.08
N_A_PS_PB: 2690
N_B_PS_PB: 7780

# Sweeping Residual
DESIRED_RESIDUAL: 0.1


