#
# Mole fraction of A
A_RAW: 0.25

# Thermo model

# Options for GIBBS are: "FH", "UNIFAC", "PCSAFT", "TaylorApproxFullFH", "TaylorApproxLogOnlyFH"
GIBBS: FH


# Options for SIZE_DISPARITY are: "SMALL", "LARGE"
SIZE_DISPARITY: SMALL

# Mobility model. Options are: "Variable" or "Constant"
MOBILITY_MODEL: Variable

# Conditions
TEMPERATURE: 298.15

#Numerics
NOISE_MAGNITUDE: 0.01
TIME_MAX: 100000
DT: 200.0
N_CELLS: 100
DOMAIN_LENGTH: 100
theta_ch: 1
TIME_STRIDE: 100
MESH_TYPE: structured
FINITE_ELEMENT: CG
FINITE_ELEMENT_ORDER: 1
# Options are: "LU" or "KRYLOV"
SOLVER_CONFIG: KRYLOV

# Options are: "Vashistha94", "He97", "PS_PMMA", "PS_PB"
MATERIAL_CHOICE: PS_PMMA

# Materials
# PS_PMMA
N_A_PS_PMMA: 500
N_B_PS_PMMA: 500

# PS_PB
N_A_PS_PB: 50
N_B_PS_PB: 50

# Sweeping Residual
DESIRED_RESIDUAL: 0.1

# Vashistha94
chi_AB_Vashistha: 0.01
N_A_Vashistha: 1000
N_B_Vashistha: 1000
## Sym Quartic Polynomial
A_SYM_Vashistha: 0.0013750000000922432

# He97
chi_AB_He: 0.004
N_A_He: 800
N_B_He: 1400
## Sym Quartic Polynomial
A_SYM_He: 0.00528125000004125