# mole fraction of A
A_RAW: 0.5

# Thermo model
GIBBS: FH

# Materials
MATERIAL_CHOICE: PS_PMMA

#Numerics
NOISE_MAGNITUDE: 0.05
TIME_MAX: 40000
DT: 1
N_CELLS: 250
DOMAIN_LENGTH: 250
theta_ch: 0.5
TIME_STRIDE: 100
MESH_TYPE: structured
FINITE_ELEMENT: CG
FINITE_ELEMENT_ORDER: 1


# PS_PMMA
## FH
chi_AB_PS_PMMA: 0.02
N_A_PS_PMMA: 1000
N_B_PS_PMMA: 1000

## PC_SAFT


# PS_PB
## FH
chi_AB_PS_PB: 0.005
N_A_PS_PB: 1000
N_A_PS_PB: 1000


