#
# Mole fraction of A
A_RAW: 0.789

# Thermo model
# Options for GIBBS are: "FH", "UNIFAC", "PCSAFT", "TaylorApproxFullFH", "TaylorApproxLogOnlyFH"
GIBBS: "PCSAFT"

# Options for SIZE_DISPARITY are: "SMALL", "LARGE"
SIZE_DISPARITY: SMALL

# Mobility model
MOBILITY_MODEL: Constant

# Conditions
TEMPERATURE: 298.15

# Materials
MATERIAL_CHOICE: ["PB","PS"]
N_A: 50
N_B: 50

#Numerics
NOISE_MAGNITUDE: 0.01
TIME_MAX: 1000
DT: 1
N_CELLS: 20
DOMAIN_LENGTH: 10
theta_ch: 1
TIME_STRIDE: 10
MESH_TYPE: structured
FINITE_ELEMENT: CG
FINITE_ELEMENT_ORDER: 1
SOLVER_CONFIG: LU