#
# Mole fraction of A
A_RAW: 0.5

# Thermo model
GIBBS: FH

# Materials
MATERIAL_CHOICE: PS_PMMA

#Numerics
NOISE_MAGNITUDE: 0.01
TIME_MAX: 2
DT: 0.001
N_CELLS: 200
DOMAIN_LENGTH: 250
theta_ch: 1
TIME_STRIDE: 500
MESH_TYPE: structured
FINITE_ELEMENT: CG
FINITE_ELEMENT_ORDER: 2
SOLVER_CONFIG: KRYLOV


# PS_PMMA
## FH
chi_AB_PS_PMMA: 0.509
N_A_PS_PMMA: 1000
N_B_PS_PMMA: 1

## PC_SAFT


# PS_PB
## FH
chi_AB_PS_PB: 0.06
N_A_PS_PB: 1000
N_A_PS_PB: 1000

# Sweeping Residual
DESIRED_RESIDUAL: 0.1


