#
# Mole fraction of A
A_RAW: 0.211

# Thermo model

# Options for GIBBS are: "FH", "UNIFAC", "PCSAFT", "TaylorApproxFullFH", "TaylorApproxLogOnlyFH"
GIBBS: "FH"


# Options for SIZE_DISPARITY are: "SMALL", "LARGE"
SIZE_DISPARITY: SMALL

# Mobility model
MOBILITY_MODEL: Constant

# Conditions
TEMPERATURE: 298.15

#Numerics
NOISE_MAGNITUDE: 0.01
TIME_MAX: 1000
DT: 1
N_CELLS: 20
DOMAIN_LENGTH: 10
theta_ch: 1
TIME_STRIDE: 10
MESH_TYPE: structured
FINITE_ELEMENT: CG
FINITE_ELEMENT_ORDER: 1
SOLVER_CONFIG: LU

MATERIAL_CHOICE: "Vashistha94"

# Materials
# PS_PMMA
N_A_PS_PMMA: 50
N_B_PS_PMMA: 50

# PS_PB
N_A_PS_PB: 50
N_B_PS_PB: 50

# Sweeping Residual
DESIRED_RESIDUAL: 0.1

# Vashistha94
chi_AB_Vashistha: 0.01
N_A_Vashistha: 1000
N_B_Vashistha: 1000
## Sym Quartic Polynomial
A_SYM_Vashistha: 0.0013750000000922432

# He97
chi_AB_He: 0.004
N_A_He: 800
N_B_He: 1400
## Sym Quartic Polynomial
A_SYM_He: 0.00528125000004125